/** @format */
export const SET_NAV_HEIGHT = 'SET_NAV_HEIGHT'; // 

export const SET_STATUSBAR_HEIGHT = 'SET_STATUSBAR_HEIGHT';

export const SET_USER_INFO = 'SET_USER_INFO';

export const SET_XF_DOWNLOAD_NORMSLIST = 'SET_XF_DOWNLOAD_NORMSLIST';

export const DELETE_XF_DOWNLOAD_NORMSLIST = 'DELETE_XF_DOWNLOAD_NORMSLIST';